package onion.tools.doc

import java.io.{File, PrintWriter}
import java.nio.charset.StandardCharsets

/**
 * Writes a small static HTML documentation site to an output directory:
 * an `index.html` listing every type and one `<TypeName>.html` per type.
 */
object HtmlWriter {

  private val Css: String =
    """
      |body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      |       margin: 0; color: #1b1f23; background: #fff; line-height: 1.55; }
      |.container { max-width: 900px; margin: 0 auto; padding: 2rem 1.5rem 4rem; }
      |header { border-bottom: 1px solid #e1e4e8; margin-bottom: 1.5rem; }
      |h1 { font-size: 1.8rem; }
      |h2 { font-size: 1.3rem; border-bottom: 1px solid #eee; padding-bottom: .3rem; margin-top: 2rem; }
      |h3 { font-size: 1.05rem; margin: 1.4rem 0 .3rem; }
      |a { color: #0366d6; text-decoration: none; }
      |a:hover { text-decoration: underline; }
      |code { background: #f6f8fa; padding: .15em .4em; border-radius: 4px;
      |       font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: .9em; }
      |pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }
      |pre code { background: none; padding: 0; }
      |.member { border-left: 3px solid #e1e4e8; padding: .2rem 0 .2rem 1rem; margin: 1rem 0; }
      |.sig { display: block; background: #f6f8fa; padding: .5rem .7rem; border-radius: 6px; margin-bottom: .4rem; }
      |.kind-tag { display: inline-block; font-size: .7rem; text-transform: uppercase; letter-spacing: .04em;
      |            background: #0366d6; color: #fff; padding: .1rem .45rem; border-radius: 3px; vertical-align: middle; }
      |.tags { margin: .4rem 0; }
      |.tags dt { font-weight: 600; }
      |.tags dd { margin: 0 0 .4rem 1rem; }
      |.type-list { list-style: none; padding: 0; }
      |.type-list li { margin: .35rem 0; }
      |footer { margin-top: 3rem; color: #6a737d; font-size: .85rem; }
      |""".stripMargin

  private def esc(s: String): String = Markdown.escape(s)

  private def page(title: String, bodyHtml: String): String =
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>${esc(title)}</title>
       |<style>$Css</style>
       |</head>
       |<body>
       |<div class="container">
       |$bodyHtml
       |<footer>Generated by oniondoc</footer>
       |</div>
       |</body>
       |</html>
       |""".stripMargin

  /** Write the whole site for the given documented files into `outDir`. */
  def write(files: List[DocFile], outDir: File): Unit = {
    if (!outDir.exists()) outDir.mkdirs()
    val allTypes = files.flatMap(_.types)
    writeFile(new File(outDir, "index.html"), page("oniondoc", renderIndex(files)))
    for (t <- allTypes) {
      writeFile(new File(outDir, s"${t.name}.html"), page(t.name, renderType(t)))
    }
  }

  private def writeFile(f: File, content: String): Unit = {
    val w = new PrintWriter(f, StandardCharsets.UTF_8.name())
    try w.write(content) finally w.close()
  }

  // ---- Rendering ------------------------------------------------------------

  private def renderIndex(files: List[DocFile]): String = {
    val sb = new StringBuilder
    sb.append("<header><h1>oniondoc</h1></header>\n")
    for (file <- files if file.types.nonEmpty) {
      sb.append(s"<h2>${esc(file.sourceName)}</h2>\n")
      sb.append("<ul class=\"type-list\">\n")
      for (t <- file.types) {
        val summary = t.doc.map(_.summary).filter(_.nonEmpty).map(s => s" — ${esc(s)}").getOrElse("")
        sb.append(s"""<li><span class="kind-tag">${esc(t.kind)}</span> <a href="${esc(t.name)}.html">${esc(t.name)}</a>$summary</li>\n""")
      }
      sb.append("</ul>\n")
    }
    sb.toString
  }

  private def renderType(t: DocType): String = {
    val sb = new StringBuilder
    sb.append("<header>\n")
    sb.append(s"""<h1><span class="kind-tag">${esc(t.kind)}</span> ${esc(t.name)}</h1>\n""")
    sb.append(s"<pre><code>${esc(t.signature)}</code></pre>\n")
    sb.append("</header>\n")
    sb.append(s"""<p><a href="index.html">← Index</a></p>\n""")

    t.doc.foreach { d =>
      if (d.body.nonEmpty) sb.append(Markdown.toHtml(d.body)).append("\n")
      renderTypeTags(d, sb)
    }

    if (t.constructors.nonEmpty) {
      sb.append("<h2>Constructors</h2>\n")
      t.constructors.foreach(m => renderMember(m, sb))
    }
    if (t.methods.nonEmpty) {
      sb.append("<h2>Methods</h2>\n")
      t.methods.foreach(m => renderMember(m, sb))
    }
    if (t.fields.nonEmpty) {
      sb.append("<h2>Fields</h2>\n")
      t.fields.foreach(m => renderMember(m, sb))
    }
    sb.toString
  }

  private def renderTypeTags(d: DocComment, sb: StringBuilder): Unit = {
    val items = scala.collection.mutable.ListBuffer[(String, String)]()
    d.deprecated.foreach(t => items += (("Deprecated", t.desc)))
    d.since.foreach(t => items += (("Since", t.desc)))
    d.author.foreach(t => items += (("Author", t.desc)))
    d.see.foreach(t => items += (("See", t.desc)))
    if (items.nonEmpty) {
      sb.append("<dl class=\"tags\">\n")
      items.foreach { case (k, v) => sb.append(s"<dt>${esc(k)}</dt><dd>${Markdown.escape(v)}</dd>\n") }
      sb.append("</dl>\n")
    }
  }

  private def renderMember(m: DocMember, sb: StringBuilder): Unit = {
    sb.append("<div class=\"member\">\n")
    sb.append(s"<code class=\"sig\">${esc(m.signature)}</code>\n")
    m.doc.foreach { d =>
      if (d.body.nonEmpty) sb.append(Markdown.toHtml(d.body)).append("\n")
      renderMemberTags(d, sb)
    }
    sb.append("</div>\n")
  }

  private def renderMemberTags(d: DocComment, sb: StringBuilder): Unit = {
    val hasTags = d.params.nonEmpty || d.returns.isDefined || d.throwsTags.nonEmpty ||
      d.deprecated.isDefined || d.since.isDefined || d.see.nonEmpty
    if (!hasTags) return
    sb.append("<dl class=\"tags\">\n")
    d.deprecated.foreach(t => sb.append(s"<dt>Deprecated</dt><dd>${esc(t.desc)}</dd>\n"))
    if (d.params.nonEmpty) {
      sb.append("<dt>Parameters</dt>\n")
      d.params.foreach(p => sb.append(s"<dd><code>${esc(p.arg)}</code> — ${esc(p.desc)}</dd>\n"))
    }
    d.returns.foreach(r => sb.append(s"<dt>Returns</dt><dd>${esc(r.desc)}</dd>\n"))
    if (d.throwsTags.nonEmpty) {
      sb.append("<dt>Throws</dt>\n")
      d.throwsTags.foreach(x => sb.append(s"<dd><code>${esc(x.arg)}</code> — ${esc(x.desc)}</dd>\n"))
    }
    d.since.foreach(t => sb.append(s"<dt>Since</dt><dd>${esc(t.desc)}</dd>\n"))
    d.see.foreach(t => sb.append(s"<dt>See</dt><dd>${esc(t.desc)}</dd>\n"))
    sb.append("</dl>\n")
  }
}
